import "./styles/globals.scss";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import Hero from "./components/Hero";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="it">
      <body>
        <div className="p-4 overflow-y-auto whitespace-nowrap">
          <header className="flex  bg-cyan-800 justify-between">
            <Nav />
          </header>
          <main className="p-0">{children}</main>
          <footer
            style={{
              background: "#666",
              boxShadow: "0 1px 1px 0 rgba(0, 0, 0, 0.12)",
            }}
            className="w-full h-full  "
          >
          <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
