const galleryItems = [
  {
    id: 1,
    imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Garanzia",
    description: "qualità del prodotto",
  },
  {
    id: 2,
    imageSrc: "/productions/1.jpg",
    imageAlt:"done all",
    title: "Minimo",
    description: "Tempo di consegna stimato",
  },
  {
    id: 3,
   imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Professionale",
    description: "squadra",
  },
  {
    id: 4,
    imageSrc: "/productions/1.jpg",
    imageAlt: "Consegna",
    title: "Consegna",
    description: "prodotti",
  },
  {
    id: 5,
   imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Ordini",
    description: "da 10 mq. M.",
  },
  {
    id: 6,
    imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "con partenza",
  },
  {
    id: 7,
   imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Tutta la vita",
    description: "garanzia",
  },
  {
    id: 8,
   imageSrc: "/productions/1.jpg",
    imageAlt:"done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
    {
    id: 9,
    imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
      {
    id: 10,
   imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
        {
    id: 11,
   imageSrc: "/productions/1.jpg",
    imageAlt:"done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
          {
    id: 12,
   imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
            {
    id: 13,
    imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
              {
    id: 14,
    imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
                {
    id: 15,
    imageSrc: "/productions/1.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
                  {
    id: 16,
    imageSrc: "/productions/1.jpg",
    imageAlt:"done all",
    title: "Misurazioni",
    description: "Gratuito",
  }
];
export default galleryItems