export { default as Facebook } from "./Facebook.svg"
export { default as Instagram } from "./Instagram.svg"
export { default as Linkedin } from "./Linkedin.svg"
export { default as Twitter } from "./Twitter.svg"
export { default as MapPin } from "./MapPin.svg"
export { default as MenuMobil } from "./MenuMobil.svg"