const galleryItems = [
  {
    id: "1",
    imageSrc: "/gallery/piping1x2.jpg",
    imageAlt: "done all",
    title: "Garanzia",
    description: "qualità del prodotto",
  },
  {
    id: "2",
    imageSrc: "/gallery/piping4x2.jpg",
    imageAlt:"done all",
    title: "Minimo",
    description: "Tempo di consegna stimato",
  },
  {
    id: "3",
   imageSrc: "/gallery/piping3x2.jpg",
    imageAlt: "done all",
    title: "Professionale",
    description: "squadra",
  },
  {
    id: "4",
    imageSrc: "/gallery/piping13x2.jpg",
    imageAlt: "Consegna",
    title: "Consegna",
    description: "prodotti",
  },
  {
    id: "5",
   imageSrc: "/gallery/piping7x2.jpg",
    imageAlt: "done all",
    title: "Ordini",
    description: "da 10 mq. M.",
  },
  {
    id: "6",
    imageSrc: "/gallery/piping6x2.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "con partenza",
  },
  {
    id: "7",
   imageSrc: "/gallery/piping5x2.jpg",
    imageAlt: "done all",
    title: "Tutta la vita",
    description: "garanzia",
  },
  {
    id: "8",
   imageSrc: "/gallery/piping8x2.jpg",
    imageAlt:"done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
    {
    id: "9",
    imageSrc: "/gallery/piping9x2.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
      {
    id: "10",
   imageSrc: "/gallery/piping10x2.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
        {
    id: "11",
   imageSrc: "/gallery/piping11x2.jpg",
    imageAlt:"done all",
    
    title: "Misurazioni",
    description: "Gratuito",
    },
          {
    id: "12",
   imageSrc: "/gallery/piping2x2.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
            {
    id: "13",
    imageSrc: "/gallery/piping12x2.jpg",
    imageAlt: "done all",
    title: "Misurazioni",
    description: "Gratuito",
    },
      
];
export default galleryItems